//
//  Apps.swift
//  AWSAuthCore
//
//  Created by Christopher Deck on 4/16/18.
//

//
//  Apps.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//
import Foundation
import UIKit
import AWSDynamoDB

class Apps: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _appId: Int? = 0
    @objc var _displayName: String?
    @objc var _platform: String?
    @objc var _uRL: String?
    
    class func dynamoDBTableName() -> String {
        
        return "addme-mobilehub-1337549400-Apps"
    }
    
    class func hashKeyAttribute() -> String {
        
        return "_userId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
            "_appId" : "appId",
            "_displayName" : "DisplayName",
            "_platform" : "Platform",
            "_uRL" : "URL",
        ]
    }
}
